### ISSUE TITLE
[ERR] null (3b5ca34b) Unable to load DLL 'e_sqlite3

### ISSUE THREAD

**Issue by bytesizedalex** [Still34/PsvDecryptCore#4]
On program run I get the following error - 

```
2018-09-22T17:16:09.7940283+01:00  [WRN] Press any key to start decryption... (3b5ca34b)
2018-09-22T17:16:11.8877905+01:00  [ERR] null (3b5ca34b)
System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.DllNotFoundException: Unable to load DLL 'e_sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_libversion_number()
   at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
   at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at Microsoft.Data.Sqlite.Utilities.BundleInitializer.Initialize()
   at Microsoft.Data.Sqlite.SqliteConnection..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at PsvDecryptCore.Services.DecryptionEngine.<StartAsync>d__5.MoveNext() in C:\projects\psvdecryptcore\PsvDecryptCore\Services\DecryptionEngine.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PsvDecryptCore.Program.<StartAsync>d__5.MoveNext() in C:\projects\psvdecryptcore\PsvDecryptCore\Program.cs:line 61
2018-09-22T17:16:11.8878722+01:00  [INF] Finished after 00:00:01.0363130. (3b5ca34b)
2018-09-22T17:16:11.8878851+01:00  [INF] Press any key to exit. (3b5ca34b)
```

**Comment by Still34** [comment]
What OS is this running on and are you running a OS-specific release? (i.e. not running via `dotnet PsvDecryptCore.dll`, but the compiled executable)

**Comment by bytesizedalex** [comment]
OS details - Microsoft Windows 8.1 Pro x64

Downloaded the latest x64 release from the link, PsvDecryptCore-a867840f47a5baf17d8f24710e78baab563d0d40-win-x64.zip

**Comment by Still34** [comment]
Try the [latest release](https://ci.appveyor.com/api/buildjobs/o7cct3mvaqa2k6cb/artifacts/PsvDecryptCore-f400a0e75025a9e893fcec1c689fec010241e789-win-x64.zip) instead. AppVeyor displayed an older version since I rebuilt from that older commit last week.

**Comment by bytesizedalex** [comment]
That version seems to be working - I've got a few courses for it to run through but happy to close this issue as the original problem appears resolved.
